services:
  db:
    image: postgres:16.9-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - network

  app:
    build: ./app/
    env_file: .env
    restart: always
    ports:
      - 9000:8000
    depends_on:
      - db
    networks:
      - network
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app/

volumes:
  pg_data:

networks:
  network: